// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABOSOGN7BNHAqQWDQ7j1q9ItBj-iE8PaA',
    appId: '1:250921547860:web:da5b6e7cb3328c933e55c1',
    messagingSenderId: '250921547860',
    projectId: 'shoutout-d907e',
    authDomain: 'shoutout-d907e.firebaseapp.com',
    databaseURL: 'https://shoutout-d907e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'shoutout-d907e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXFaQG4tlMsdgDo8UF-6VOXyuMNaATLeo',
    appId: '1:250921547860:android:81f5ea39425a169f3e55c1',
    messagingSenderId: '250921547860',
    projectId: 'shoutout-d907e',
    databaseURL: 'https://shoutout-d907e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'shoutout-d907e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjduNTdBP6maTsjZl4KuUConNndnVq7Oo',
    appId: '1:250921547860:ios:9caabb2e015533063e55c1',
    messagingSenderId: '250921547860',
    projectId: 'shoutout-d907e',
    databaseURL: 'https://shoutout-d907e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'shoutout-d907e.appspot.com',
    iosBundleId: 'com.example.shoutOutApp',
  );
}
